name: Sync From Git To Azure

on: 
  push:
    branches: [main]
    
jobs:
  sync_from_git_to_azure:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup environment variables
      run: |
        echo ::set-env name=AZUREPAT::${{ secrets.AZUREPAT }}
        echo ::set-env name=AZUSERNAME::${{ secrets.AZUSERNAME }}
        echo ::set-env name=AZUSER_EMAIL::${{ secrets.AZUSER_EMAIL }}
        echo ::set-env name=AZORG::${{ secrets.AZORG }}
    - name: Git clone repo
      run: |
        git clone https://github.com/AlekWithK/BuildManager
        cd reponame
        rm -rf .git
    - name: Clone to Azure DevOps Repo
      run: |
        cd ..
        GIT_CMD_REPOSITORY="https://$AZUSERNAME:$AZUREPAT@dev.azure.com/$AZORG/BuildManager/_git/BuildManager" 
        git clone $GIT_CMD_REPOSITORY
    - name: Copy files from git repro to azure repro
      run: |
        cp -r BuildManager/* BuildManager/
    - name: Configure user in azure repro
      run: |
        cd BuildManager
        git config --global user.email "$AZUSER_EMAIL"
        git config --global user.name "$AZUSERNAME"
    - name: Commit and Push to azure
      run: |
        git add .
        git commit -m "sync from git to azure"
        git push
